### ISSUE TITLE
Plug-ins don't work.

### ISSUE THREAD

**Issue by kiharaneko** [vunguyentuan/vscode-css-variables#8]
I installed a plugin and it doesn't work.
I would like to know how to use this plugin in detail.

**Comment by franktopel** [comment]
Doesn't do anything at for me either.

Here's my `settings.json`:

```json
{
    "cssVariables.lookupFiles": [
        "src/css/variables/_colors.variables.css"
    ]
}
```
<img width="508" alt="image" src="https://user-images.githubusercontent.com/10668603/127149286-8cf4137c-23ad-4b3c-b060-6e6e9be5d082.png">

**Comment by literalpie** [comment]
The extension works fine for me. I have a similar settings to what @franktopel has. If it makes a difference, I'm on a Mac and using scss files.

**Comment by AlexisWalravens** [comment]
Doesn't work for me either, I'm on mac and using PostCSS (.css) files.

**Comment by neoglez** [comment]
Neither for me

**Comment by neoglez** [comment]
> Neither for me

Well, it does work (shame on me :( ). By looking into the code, I was able to find the problem:
In `setting.json` you have to correctly configure the `json` object:
```
{
    "cssVariables": {
      "lookupFiles": [
        "my/public/or/whatever/variables.css",
      ]
    }
}
```
Be **really** sure that your path is correct (my path was not).
Now, regarding the completion, for the most part works well. However, if you already typed `var(--`, the plug in completes with `var(--`, therefore, inserting var twice`var(var(--some-css-variable))`.

**Comment by vunguyentuan** [comment]
@neoglez I've published a new version 2, no need configuration file

**Comment by vunguyentuan** [comment]
@AlexisWalravens could you share your variables.css file and also how the folder structure looks like?

**Comment by vunguyentuan** [comment]
@AlexisWalravens also try to reload the vscode

**Comment by AlexisWalravens** [comment]
Of course, here it is: https://github.com/AlexisWalravens/postcss-boilerplate

**Comment by vunguyentuan** [comment]
@AlexisWalravens This should be fixed on the latest version. Thanks, Alex!

**Comment by AlexisWalravens** [comment]
@vunguyentuan Thanks for you plugin and you reactivity.

Sadly when setting the file to PostCSS it still doesn't work.
(I checked I have the latest version `v2.1.3 -  Last updated 23/12/2021, 02:19:17`)

**Comment by vunguyentuan** [comment]
@AlexisWalravens I think this is a bigger issue postcss vscode plugin not this plugin https://github.com/csstools/postcss-language/issues/2.
